/* tslint:disable */
/* eslint-disable */
export const memory: WebAssembly.Memory;
export function __wbg_soil_free(a: number): void;
export function __wbg_get_soil_soil_id(a: number): number;
export function __wbg_set_soil_soil_id(a: number, b: number): void;
export function __wbg_get_soil_top_level(a: number): number;
export function __wbg_set_soil_top_level(a: number, b: number): void;
export function __wbg_get_soil_base_level(a: number): number;
export function __wbg_set_soil_base_level(a: number, b: number): void;
export function __wbg_get_soil_phi(a: number): number;
export function __wbg_set_soil_phi(a: number, b: number): void;
export function __wbg_get_soil_gamma(a: number): number;
export function __wbg_set_soil_gamma(a: number, b: number): void;
export function __wbg_get_soil_c(a: number): number;
export function __wbg_set_soil_c(a: number, b: number): void;
export function __wbg_get_soil_su(a: number): number;
export function __wbg_set_soil_su(a: number, b: number): void;
export function __wbg_groundmodel_free(a: number): void;
export function __wbg_loadcomb_free(a: number): void;
export function __wbg_ec7loads_free(a: number): void;
export function __wbg_loads_free(a: number): void;
export function __wbg_foundation_free(a: number): void;
export function __wbg_get_foundation_b(a: number): number;
export function __wbg_set_foundation_b(a: number, b: number): void;
export function __wbg_get_foundation_l(a: number): number;
export function __wbg_set_foundation_l(a: number, b: number): void;
export function __wbg_get_foundation_level(a: number): number;
export function __wbg_set_foundation_level(a: number, b: number): void;
export function __wbg_get_foundation_inclination(a: number): number;
export function __wbg_set_foundation_inclination(a: number, b: number): void;
export function ecc_b(a: number): number;
export function ecc_l(a: number): number;
export function eff_b(a: number, b: number): number;
export function eff_l(a: number, b: number): number;
export function eff_a(a: number, b: number): number;
export function n_q(a: number): number;
export function n_c(a: number): number;
export function n_g(a: number): number;
export function b_g(a: number, b: number): number;
export function b_c(a: number, b: number): number;
export function b_c_undrained(a: number): number;
export function s_q(a: number, b: number): number;
export function s_g(a: number): number;
export function s_c(a: number, b: number): number;
export function s_c_undrained(a: number): number;
export function resultant_action(a: number, b: number): number;
export function resultant_action_angle(a: number, b: number): number;
export function m_b(a: number): number;
export function m_l(a: number): number;
export function m(a: number, b: number): number;
export function i_q(a: number, b: number, c: number): number;
export function i_g(a: number, b: number, c: number): number;
export function i_c(a: number, b: number, c: number): number;
export function i_c_undrained(a: number, b: number, c: number): number;
export function drained_bearing_capacity(a: number, b: number, c: number, d: number): number;
export function undrained_bearing_capacity(a: number, b: number, c: number, d: number): number;
export function bearing_capacity_check(a: number, b: number, c: number, d: number): number;
export function undrained_bearing_capacity_check(a: number, b: number, c: number, d: number): number;
export function __wbg_partialfactors_free(a: number): void;
export function __wbg_get_partialfactors_g_g_unfav(a: number): number;
export function __wbg_get_partialfactors_g_g_fav(a: number): number;
export function __wbg_get_groundmodel_ground_level(a: number): number;
export function __wbg_get_groundmodel_gw_level(a: number): number;
export function __wbg_get_partialfactors_g_q_unfav(a: number): number;
export function __wbg_get_partialfactors_g_q_fav(a: number): number;
export function b_q(a: number, b: number): number;
export function __wbg_set_partialfactors_g_g_unfav(a: number, b: number): void;
export function __wbg_set_partialfactors_g_g_fav(a: number, b: number): void;
export function __wbg_set_groundmodel_ground_level(a: number, b: number): void;
export function __wbg_set_groundmodel_gw_level(a: number, b: number): void;
export function __wbg_set_partialfactors_g_q_unfav(a: number, b: number): void;
export function __wbg_set_partialfactors_g_q_fav(a: number, b: number): void;
export function stroud_f1(a: number): number;
export function stroud_f2(a: number): number;
export function spt_to_cu(a: number, b: number): number;
export function spt_to_mv(a: number, b: number): number;
export function cu_val_to_desc(a: number): number;
export function mv_val_to_desc(a: number): number;
export function mv_to_e_dash(a: number, b: number, c: number): void;
export function a_line_check(a: number, b: number): number;
export function plasticity_check(a: number): number;
export function __wbg_hoekbrownmodel_free(a: number): void;
export function __wbg_get_hoekbrownmodel_gsi(a: number): number;
export function __wbg_set_hoekbrownmodel_gsi(a: number, b: number): void;
export function __wbg_get_hoekbrownmodel_mi(a: number): number;
export function __wbg_set_hoekbrownmodel_mi(a: number, b: number): void;
export function __wbg_get_hoekbrownmodel_d(a: number): number;
export function __wbg_set_hoekbrownmodel_d(a: number, b: number): void;
export function __wbg_get_hoekbrownmodel_ucs(a: number): number;
export function __wbg_set_hoekbrownmodel_ucs(a: number, b: number): void;
export function hoekbrownmodel_mb(a: number): number;
export function hoekbrownmodel_s(a: number): number;
export function hoekbrownmodel_a(a: number): number;
export function rock_e_val(a: number): number;
export function mc_phi_conv(a: number, b: number): number;
export function mcc_dash_conv(a: number, b: number): number;
export function coefficient_uniformity(a: number, b: number): number;
export function easy_digging(a: number, b: number): number;
export function hard_digging(a: number, b: number): number;
export function easy_ripping(a: number, b: number): number;
export function hard_ripping(a: number, b: number): number;
export function very_hard_ripping(a: number, b: number): number;
export function extreme_ripping(a: number, b: number): number;
export function excavability_assessment(a: number, b: number): number;
export function peak_phi_from_pi_lb_nc_clay(a: number): number;
export function peak_phi_from_pi_bestest_nc_clay(a: number): number;
export function peak_phi_from_pi_lb_oc_clay(a: number, b: number): void;
export function peak_phi_from_pi_bestest_oc_clay(a: number, b: number): void;
export function __wbg_acecresults_free(a: number): void;
export function __wbg_bresd1tests_free(a: number): void;
export function soil_particle_size_description(a: number): number;
export function __wbg_gradingtestsummary_free(a: number): void;
export function grading_test_result(a: number): number;
export function __wbg_soildescription_free(a: number): void;
export function __wbg_soilmodel_free(a: number): void;
export function soilmodel_angle_friction_factored(a: number, b: number, c: number): void;
export function soilmodel_undrained_shear_strength_factored(a: number, b: number, c: number): void;
export function soilmodel_clay_strength_description(a: number): number;
export function __wbg_groundmodels_free(a: number): void;
export function groundmodels_groundwater_depth(a: number): number;
export function groundmodels_number_of_soil_layers(a: number): number;
export function groundmodels_get_soil_at_level(a: number, b: number, c: number): void;
export function __wbg_gradingtestsample_free(a: number): void;
export function __wbg_gradingtest_free(a: number): void;
export function __wbg_particlesizedescription_free(a: number): void;
export function __wbg_lwall_free(a: number): void;
export function lwall_stem_lever_arm(a: number): number;
export function lwall_stem_lever_arm_surcharge(a: number): number;
export function lwall_base_lever_arm(a: number): number;
export function __wbg_backfill_free(a: number): void;
export function active_earth_pressure_on_wall_self_weight(a: number, b: number, c: number): number;
export function active_earth_pressure_on_wall_surcharge(a: number, b: number, c: number, d: number): number;
export function driving_force(a: number, b: number, c: number, d: number): number;
export function driving_moment(a: number, b: number, c: number, d: number): number;
export function resisting_force(a: number, b: number): number;
export function resisting_moment(a: number, b: number): number;
export function overturning_utilisation(a: number, b: number, c: number, d: number): number;
export function deg_to_rad(a: number): number;
export function k0(a: number): number;
export function rankine_ka(a: number): number;
export function rankine_kp(a: number): number;
export function coulomb_ka(a: number, b: number, c: number, d: number): number;
export function coulomb_kp(a: number, b: number, c: number, d: number): number;
export function ec7_phi_factor(a: number, b: number): number;
export function greet(a: number, b: number): void;
export function __wbindgen_add_to_stack_pointer(a: number): number;
export function __wbindgen_malloc(a: number): number;
export function __wbindgen_realloc(a: number, b: number, c: number): number;
